apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opendevx-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Sanyam-saxena/OpenDevX.git'
    targetRevision: HEAD
    path: infrastructure/kubernetes/helm/opendevx
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: opendevx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
